[package]
name = "simdeez"
version = "0.2.1"
authors = ["Jack Mott <jack.mott@gmail.com>"]
description = "SIMD library to abstract over different instruction sets and widths"
license = "Apache-2.0/MIT"
documentation = "https://docs.rs/simdeez/"
readme = "README.md"
keywords = ["SIMD", "avx2", "sse", "neon","performance"]
repository = "https://github.com/jackmott/simdeez"
categories = ["hardware-support","science"]

